version:   "{build}"
platform:  x64
test:      on
build:     off
deploy:    off
skip_tags: true

branches:
    only:
        - master

environment:
    matrix:
        - ATOM_CHANNEL: stable
        - ATOM_CHANNEL: beta

install:
    - ps: Install-Product node $env:nodejs_version

test_script:
    - ps: (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
